//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axsis.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public long UsuarioId { get; set; }
        public short SexoId { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Contraseña { get; set; }
        public bool Estatus { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public long UsuarioCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public long UsuarioModificacion { get; set; }
    
        public virtual Sexo Sexo { get; set; }
    }
}
